### ISSUE TITLE
How to test the detector?

### ISSUE THREAD

**Issue by romulogcerqueira** [VarunBal/forklift-detector#1]
I could not install and run the detector properly.
No instructions are available in the repository.

**Comment by VarunBal** [comment]
The trained model is not included in the repository. Only the data and the files necessary for training the model are included, so you will need to train the model using that.

**Comment by romulogcerqueira** [comment]
Thanks for your quick reply, @VarunBal .

How can I use the repository resources (data + files) to train the model? Are any instructions available?

**Comment by VarunBal** [comment]
Hi, you can refer to the "forklift_detection_train.ipynb" and "forklift_detect.ipynb" notebooks and run them on Google colab for training. 

Note that you might need to manually upload the required files in the repo to the google colab instance.

For any queries regarding yolo training, you can refer to the [original darknet repo](https://github.com/pjreddie/darknet.git) or the [latest maintained darknet repo](https://github.com/AlexeyAB/darknet.git).

**Comment by romulogcerqueira** [comment]
Hi @VarunBal, thanks again.

I faced an error when downloading the data:
![image](https://user-images.githubusercontent.com/4711921/173206965-37cd9ba4-a169-4e54-b337-240e383410d5.png)

Link: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Do you know how to solve this issue?
